=== AndreiKuralenya/Plane/by/bsu/airline/Planes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.com/Planes"
	xmlns:tns="http://www.example.com/Planes">
	<element name="planes">

		<complexType>
			<sequence>
				<element name="plane" type="tns:plane" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="plane">
		<sequence>
			<element name="name" type="string" />
			<element name="year" type="positiveInteger" />
			<element name="country" type="string" />
			<element name="characteristics" type="tns:Characteristics"
				minOccurs="1" maxOccurs="unbounded" />
			<element name="parameters" type="tns:Parameters" minOccurs="1"
				maxOccurs="unbounded" />
			<element name="price" type="positiveInteger" />
		</sequence>
		<attribute name="ID">
			<simpleType>
				<restriction base="positiveInteger">
					<pattern value="(\\w){0, 3}" />
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="view">
			<simpleType>
				<restriction base="string">
					<enumeration value="passanger"></enumeration>
					<enumeration value="capasity"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
		<attribute name="aircompany" type="string" use="required" />
	</complexType>
	<complexType name="Characterictics">
		<sequence>
			<element name="capasity" type="positiveInteger" />
			<element name="passanger" type="positiveInteger" />
			<element name="fuel-weight" type="positiveInteger" />
			<element name="cruising-speed" type="positiveInteger" />
			<element name="range" type="positiveInteger" />
			<element name="practical-ceiling" type="positiveInteger" />
		</sequence>
	</complexType>
	<complexType name="Parameters">
		<sequence>
			<element name="length" type="positiveInteger" />
			<element name="height" type="positiveInteger" />
			<element name="width" type="positiveInteger" />
		</sequence>
	</complexType>
</schema>

=== AndreiKuralenya/Plane/by/bsu/airline/Plane.xml
<?xml version="1.0" encoding="UTF-8"?>
<planes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:ns="http://www.example.com/planes" xsi:schemaLocation="http://www.example.com/planes planes.xsd">
	<plane ID="1" view="capasity" aircompany="airline">
		<name>An-Mria</name>
		<year>1988</year>
		<country>Ukraine</country>
		<characteristics>
			<capacity>250</capacity>
			<passanger>300</passanger>
			<fuel-weight>300</fuel-weight>
			<cruising-speed>850</cruising-speed>
			<range>15400</range>
			<practical-ceiling>11000</practical-ceiling>
		</characteristics>
		<parameters>
			<length>84</length>
			<height>88.4</height>
			<width>18.2</width>
		</parameters>
		<price>240</price>
	</plane>
	<plane ID="2" view="passenger" aircompany="airline">
		<name>Airbus</name>
		<year>2005</year>
		<country>France</country>
		<characteristics>
			<capacity>200</capacity>
			<passanger>620</passanger>
			<fuel-weight>248</fuel-weight>
			<cruising-speed>900</cruising-speed>
			<range>15200</range>
			<practical-ceiling>13115</practical-ceiling>
		</characteristics>
		<parameters>
			<length>73</length>
			<height>79.75</height>
			<width>24</width>
		</parameters>
		<price>390</price>
	</plane>
	<plane ID="3" view="passenger" aircompany="airline">
		<name>Boeing747</name>
		<year>2010</year>
		<country>USA</country>
		<characteristics>
			<capacity>240</capacity>
			<passanger>581</passanger>
			<fuel-weight>230</fuel-weight>
			<cruising-speed>917</cruising-speed>
			<range>14100</range>
			<practical-ceiling>13000</practical-ceiling>
		</characteristics>
		<parameters>
			<length>76.3</length>
			<height>68.5</height>
			<width>19.4</width>
		</parameters>
		<price>228</price>
	</plane>
	<plane ID="4" view="capasity" aircompany="airline">
		<name>Boeing947</name>
		<year>1993</year>
		<country>USA</country>
		<characteristics>
			<capacity>320</capacity>
			<passanger>416</passanger>
			<fuel-weight>217</fuel-weight>
			<cruising-speed>912</cruising-speed>
			<range>14200</range>
			<practical-ceiling>11700</practical-ceiling>
		</characteristics>
		<parameters>
			<length>73.3</length>
			<height>69.5</height>
			<width>20.4</width>
		</parameters>
		<price>239</price>
	</plane>
</planes>
